version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: npm install
