export default {
    Pending_Evaluate_Relocate: "Pending-Evaluate&Relocate", //  for 4.2
    Pending_ClientAdvice: "Pending-ClientAdvice",
    Pending_ClientAdvise_Non_InventoryClientReturn: "Pending-ClientAdvise-Non-InventoryClientReturn",
    Pending_NCLR: "Pending-NCLR",
    Pending_IA: "Pending-IA",   // for 6.1
    Pending_IA_EQ: "Pending-IA-EQ",
    IA_InProgress: "IA-InProgress",
    Pending_ProductComponentLevelAudit: "Pending-ProductComponentLevelAudit",
    Storage_Store: "Storage-Store",
    Storage_PhysicalQuarantine: "Storage-PhysicalQuarantine",
    Storage_Returns: "Storage-Returns",
    Storage_Destruction: "Storage-Destruction",
    Storage_RetentionSamples: "Storage-RetentionSamples",
    Pending_PhysicalQuarantine: "Pending-PhysicalQuarantine",
    Pending_Outbound: "Pending-Outbound",
    Outbound_InProgress: "Outbound-InProgress",
    OK_to_Dispatch: "OK-to-Dispatch",
    Packed_Pending_Dispatch: "Packed&Pending-Dispatch",
    Pending_OutboundDispatch: "Pending-OutboundDispatch",
    Pending_OutboundReturnedToStorage: "Pending-OutboundReturnedToStorage",
    Outbound_Dispatched: "Outbound-Dispatched",
    Pending_POD: "Pending-POD",
    POD_Retrieved: "POD-Retrieved",
    POD_NA: "POD-N/A",
    Outbound_Shipment_Returned: "Outbound-Shipment-Returned",
    Pending_AOR: "Pending-AOR",
    AOR_Retrieved: "AOR-Retrieved",
    AOR_NA: "AOR-N/A",
    Pending_Destruction: "Pending-Destruction",
    Destroyed: "Destroyed",
    Pending_Labelling: "Pending-Labelling",
    Re_Labelled: "Re-Labelled",
    Pending_KitAssembly: "Pending-KitAssembly",
    KitAssembled: "KitAssembled",
    Others: "Others"
};
